export const commercePermissionCatalog = [
  { key: "dashboard.view", label: "Consulter le tableau de bord", group: "Pilotage" },
  { key: "stores.view", label: "Consulter les magasins autorisés", group: "Magasins" },
  { key: "stores.manage", label: "Gérer les magasins", group: "Magasins" },
  { key: "team.view", label: "Consulter l’équipe", group: "Équipe" },
  { key: "team.manage", label: "Gérer les comptes et rôles", group: "Équipe" },
  { key: "audit.view", label: "Consulter le journal d’audit", group: "Sécurité" },
  { key: "catalog.view", label: "Consulter le catalogue", group: "Catalogue" },
  { key: "catalog.manage", label: "Gérer le catalogue", group: "Catalogue" },
  { key: "customers.view", label: "Consulter les clients", group: "Ventes" },
  { key: "customers.manage", label: "Gérer les clients", group: "Ventes" },
  { key: "suppliers.view", label: "Consulter les fournisseurs", group: "Achats" },
  { key: "suppliers.manage", label: "Gérer les fournisseurs", group: "Achats" },
  { key: "sales.view", label: "Consulter les ventes", group: "Ventes" },
  { key: "sales.create", label: "Créer un devis ou une vente", group: "Ventes" },
  { key: "sales.approve", label: "Valider les ventes", group: "Ventes" },
  { key: "cash.view", label: "Consulter la caisse", group: "Caisse" },
  { key: "cash.manage", label: "Encaisser les règlements", group: "Caisse" },
  { key: "cash.close", label: "Clôturer une caisse", group: "Caisse" },
  { key: "stock.view", label: "Consulter les stocks", group: "Stocks" },
  { key: "stock.manage", label: "Gérer les stocks", group: "Stocks" },
  { key: "stock.receive", label: "Enregistrer les réceptions", group: "Stocks" },
  { key: "stock.issue", label: "Préparer les sorties de stock", group: "Stocks" },
  { key: "stock.transfer", label: "Transférer entre magasins", group: "Stocks" },
  { key: "inventory.view", label: "Consulter les inventaires", group: "Inventaires" },
  { key: "inventory.count", label: "Compter les articles", group: "Inventaires" },
  { key: "inventory.validate", label: "Valider les écarts d’inventaire", group: "Inventaires" },
  { key: "procurement.view", label: "Consulter les approvisionnements", group: "Achats" },
  { key: "procurement.manage", label: "Gérer les achats et commandes fournisseur", group: "Achats" },
  { key: "procurement.approve", label: "Valider les commandes d’achat", group: "Achats" },
  { key: "accounting.view", label: "Consulter la comptabilité", group: "Comptabilité" },
  { key: "treasury.view", label: "Consulter la trésorerie", group: "Comptabilité" },
  { key: "reports.view", label: "Consulter les rapports", group: "Pilotage" },
  { key: "reports.export", label: "Exporter les rapports", group: "Pilotage" },
  { key: "hr.view", label: "Consulter les dossiers du personnel", group: "Personnel" },
  { key: "hr.manage", label: "Gérer le personnel", group: "Personnel" },
  { key: "attendance.view", label: "Consulter les présences", group: "Personnel" },
  { key: "attendance.manage", label: "Gérer les présences", group: "Personnel" },
  { key: "costs.view", label: "Consulter les coûts et marges", group: "Finance" },
] as const;

export type CommercePermission = (typeof commercePermissionCatalog)[number]["key"];
export const commercePermissionKeys = new Set<string>(commercePermissionCatalog.map(({ key }) => key));

export const commerceRoleLabels: Record<string, string> = {
  GERANT: "Gérant / Directeur",
  VENDEUR: "Vendeur / Commercial",
  CAISSIER: "Caissier",
  MAGASINIER: "Magasinier",
  APPROVISIONNEMENT: "Chargé des approvisionnements",
  INVENTAIRE: "Responsable d’inventaire",
  COMPTABLE: "Comptable",
  RH: "Responsable RH / Personnel",
};
