// DebitManager authorization vocabulary: UI labels are not authorization; API policies remain the enforcement boundary.
export const permissionCatalog = [
  { key: "orders.view", label: "Consulter les commandes", group: "Commandes" },
  { key: "orders.create", label: "Créer une commande", group: "Commandes" },
  { key: "orders.prepare", label: "Préparer une commande", group: "Commandes" },
  { key: "orders.deliver", label: "Livrer une commande au client", group: "Commandes" },
  { key: "orders.receive", label: "Accuser réception d’une commande", group: "Commandes" },
  { key: "orders.handoff", label: "Remettre une commande au service", group: "Commandes" },
  { key: "tables.view", label: "Consulter le plan de salle", group: "Tables" },
  { key: "tables.manage", label: "Gérer les tables", group: "Tables" },
  { key: "stock.view", label: "Consulter le stock", group: "Stocks" },
  { key: "stock.adjust", label: "Ajuster le stock", group: "Stocks" },
  { key: "stock.receive", label: "Enregistrer une réception de livraison", group: "Stocks" },
  { key: "stock.issue", label: "Préparer une sortie de stock quotidienne", group: "Stocks" },
  { key: "stock.handoff", label: "Remettre un stock à un responsable", group: "Stocks" },
  { key: "stock.accept_counter", label: "Réceptionner une livraison du magasin comptoir", group: "Stocks" },
  { key: "stock.audit", label: "Contrôler les stocks et mouvements", group: "Pilotage" },
  { key: "stock.accept_kitchen", label: "Recevoir les vivres cuisine", group: "Stocks" },
  { key: "reports.daily_close", label: "Contrôler la clôture journalière", group: "Pilotage" },
  { key: "products.manage", label: "Gérer les produits", group: "Catalogue" },
  { key: "team.view", label: "Consulter l’équipe", group: "Équipe" },
  { key: "team.manage", label: "Gérer l’équipe", group: "Équipe" },
  { key: "finance.view", label: "Consulter la trésorerie", group: "Finance" },
  { key: "payments.create", label: "Préparer un encaissement", group: "Finance" },
  { key: "reports.view", label: "Consulter les rapports", group: "Pilotage" },
  { key: "messages.view", label: "Consulter les messages", group: "Messagerie" },
  { key: "messages.send", label: "Envoyer des messages", group: "Messagerie" },
  { key: "activities.view", label: "Consulter les activités", group: "Power" },
  { key: "activities.manage", label: "Gérer les activités", group: "Power" },
  { key: "services.view", label: "Consulter les services", group: "Power" },
  { key: "services.manage", label: "Gérer les services et leurs prix", group: "Power" },
  { key: "team.salary.manage", label: "Gérer les salaires", group: "Équipe" },
  { key: "power.view", label: "Consulter les modules Power", group: "Power" },
] as const;

export const defaultRolePermissions: Record<string, string[]> = {
  SERVEUR: ["orders.view", "orders.create", "orders.receive", "orders.deliver", "tables.view", "payments.create"],
  SUPERVISEUR: permissionCatalog.map((permission) => permission.key),
  MAGASINIER: ["stock.view", "stock.receive", "stock.issue", "stock.handoff", "products.manage"],
  GERANT: ["orders.view", "orders.prepare", "orders.handoff", "stock.view", "stock.accept_counter", "team.view", "team.manage", "tables.view", "tables.manage", "finance.view", "reports.view", "reports.daily_close", "messages.view", "messages.send"],
  BARMAN: ["orders.view", "orders.create", "stock.view", "tables.view", "payments.create"],
  SECRETAIRE: ["orders.view", "team.view", "reports.view", "messages.view", "messages.send", "tables.view"],
  COMPTABLE: ["finance.view", "reports.view"],
  APPROVISIONNEMENT: ["stock.view", "stock.receive", "stock.issue", "reports.view"],
  CUISINIER: ["orders.view", "orders.prepare", "orders.handoff"],
  CHEF_CUISINE: ["orders.view", "orders.prepare", "stock.view", "stock.accept_kitchen", "products.manage", "messages.view", "messages.send"],
  GYM: ["services.view", "payments.create", "power.view"],
  AUBERGE: ["services.view", "payments.create", "power.view"],
  LAVAGE: ["services.view", "payments.create", "power.view"],
  WIFI: ["services.view", "payments.create", "power.view"],
  SECURITE: ["power.view"],
  INVENTAIRE: ["stock.view", "stock.audit", "reports.view"],
  GERANT_ADJOINT: ["orders.view", "orders.prepare", "orders.handoff", "stock.view", "stock.accept_counter", "team.view", "team.manage", "tables.view", "tables.manage", "finance.view", "reports.view", "reports.daily_close", "messages.view", "messages.send", "activities.view", "services.view", "power.view"],
  CAISSIER: ["finance.view", "payments.create", "reports.view", "power.view"],
  ADMINISTRATEUR: permissionCatalog.map((permission) => permission.key),
};

export const roleLabels: Record<string, string> = {
  SERVEUR: "Serveur", SUPERVISEUR: "Superviseur", MAGASINIER: "Magasinier", GERANT: "Gérant", BARMAN: "Barman", SECRETAIRE: "Secrétaire", COMPTABLE: "Comptable", APPROVISIONNEMENT: "Approvisionnement", CUISINIER: "Cuisinier", CHEF_CUISINE: "Chef cuisine", SECURITE: "Sécurité", INVENTAIRE: "Chargé d’inventaire", GYM: "Équipe gym", AUBERGE: "Équipe auberge", LAVAGE: "Équipe lavage", WIFI: "Équipe Wi-Fi", GERANT_ADJOINT: "Gérant adjoint", CAISSIER: "Caissier", ADMINISTRATEUR: "Administrateur",
};
