// DebitManager authorization vocabulary: UI labels are not authorization; API policies remain the enforcement boundary.
export const permissionCatalog = [
  { key: "orders.view", label: "Consulter les commandes", group: "Commandes" },
  { key: "orders.create", label: "Créer une commande", group: "Commandes" },
  { key: "orders.prepare", label: "Préparer une commande", group: "Commandes" },
  { key: "orders.deliver", label: "Livrer une commande au client", group: "Commandes" },
  { key: "orders.receive", label: "Accuser réception d’une commande", group: "Commandes" },
  { key: "orders.handoff", label: "Remettre une commande au service", group: "Commandes" },
  { key: "tables.view", label: "Consulter le plan de salle", group: "Tables" },
  { key: "tables.manage", label: "Gérer les tables", group: "Tables" },
  { key: "stock.view", label: "Consulter le stock", group: "Stocks" },
  { key: "stock.adjust", label: "Ajuster le stock", group: "Stocks" },
  { key: "stock.receive", label: "Enregistrer une réception de livraison", group: "Stocks" },
  { key: "stock.issue", label: "Préparer une sortie de stock quotidienne", group: "Stocks" },
  { key: "stock.handoff", label: "Remettre un stock à un responsable", group: "Stocks" },
  { key: "stock.accept_counter", label: "Réceptionner une livraison du magasin comptoir", group: "Stocks" },
  { key: "stock.audit", label: "Contrôler les stocks et mouvements", group: "Pilotage" },
  { key: "stock.accept_kitchen", label: "Recevoir les vivres cuisine", group: "Stocks" },
  { key: "reports.daily_close", label: "Contrôler la clôture journalière", group: "Pilotage" },
  { key: "products.manage", label: "Gérer les produits", group: "Catalogue" },
  { key: "team.view", label: "Consulter l’équipe", group: "Équipe" },
  { key: "team.manage", label: "Gérer l’équipe", group: "Équipe" },
  { key: "finance.view", label: "Consulter la trésorerie", group: "Finance" },
  { key: "payments.create", label: "Préparer un encaissement", group: "Finance" },
  { key: "reports.view", label: "Consulter les rapports", group: "Pilotage" },
  { key: "messages.view", label: "Consulter les messages", group: "Messagerie" },
  { key: "messages.send", label: "Envoyer des messages", group: "Messagerie" },
  { key: "activities.view", label: "Consulter les activités", group: "Power" },
  { key: "activities.manage", label: "Gérer les activités", group: "Power" },
  { key: "services.view", label: "Consulter les services", group: "Power" },
  { key: "services.manage", label: "Gérer les services et leurs prix", group: "Power" },
  { key: "team.salary.manage", label: "Gérer les salaires", group: "Équipe" },
  { key: "power.view", label: "Consulter les modules Power", group: "Power" },
  { key: "quotes.view", label: "Consulter les devis et proformas", group: "Devis & Ventes" },
  { key: "quotes.create", label: "Créer et modifier des devis", group: "Devis & Ventes" },
  { key: "quotes.convert", label: "Convertir un devis en facture", group: "Devis & Ventes" },
  { key: "invoices.view", label: "Consulter les factures de vente", group: "Facturation" },
  { key: "cash.view", label: "Consulter la caisse et sessions", group: "Caisse" },
  { key: "cash.manage", label: "Encaisser les règlements et gérer la caisse", group: "Caisse" },
  { key: "cash.close", label: "Clôturer la caisse (Ticket Z)", group: "Caisse" },
  { key: "deliveries.view", label: "Consulter les bons de livraison", group: "Livraisons" },
  { key: "deliveries.confirm", label: "Confirmer la livraison et sortie de stock", group: "Livraisons" },
  { key: "returns.manage", label: "Gérer les retours clients et avoirs", group: "Livraisons" },
  { key: "purchases.view", label: "Consulter les demandes et bons de commande", group: "Approvisionnement" },
  { key: "purchases.create", label: "Créer des demandes et commandes d'achat", group: "Approvisionnement" },
  { key: "purchases.approve", label: "Valider les commandes d'achat selon seuil", group: "Approvisionnement" },
  { key: "purchases.receive", label: "Valider la réception de marchandises (BR)", group: "Approvisionnement" },
  { key: "suppliers.manage", label: "Gérer les fournisseurs", group: "Approvisionnement" },
  { key: "stock.transfers", label: "Gérer les transferts inter-dépôts", group: "Stocks" },
  { key: "inventory.view", label: "Consulter les inventaires physiques", group: "Inventaire" },
  { key: "inventory.count", label: "Saisir les comptages physiques", group: "Inventaire" },
  { key: "inventory.validate", label: "Valider les écarts et régulariser le stock", group: "Inventaire" },
  { key: "treasury.view", label: "Consulter les comptes de trésorerie et soldes", group: "Trésorerie" },
  { key: "treasury.transfer", label: "Effectuer des virements internes", group: "Trésorerie" },
  { key: "expenses.view", label: "Consulter les dépenses", group: "Dépenses" },
  { key: "expenses.create", label: "Enregistrer des dépenses", group: "Dépenses" },
  { key: "expenses.approve", label: "Valider les dépenses selon seuil", group: "Dépenses" },
  { key: "assets.view", label: "Consulter le registre des immobilisations", group: "Immobilisations" },
  { key: "assets.manage", label: "Gérer les immobilisations et amortissements", group: "Immobilisations" },
] as const;

export const defaultRolePermissions: Record<string, string[]> = {
  SERVEUR: ["orders.view", "orders.create", "orders.receive", "orders.deliver", "tables.view", "payments.create"],
  VENDEUR: ["orders.view", "orders.create", "quotes.view", "quotes.create", "quotes.convert", "invoices.view"],
  SUPERVISEUR: permissionCatalog.map((permission) => permission.key),
  MAGASINIER: ["stock.view", "stock.receive", "stock.issue", "stock.handoff", "products.manage", "deliveries.view", "deliveries.confirm", "returns.manage", "purchases.receive", "stock.transfers", "inventory.view", "inventory.count"],
  GERANT: ["orders.view", "orders.prepare", "orders.handoff", "quotes.view", "quotes.create", "quotes.convert", "invoices.view", "cash.view", "cash.manage", "cash.close", "deliveries.view", "deliveries.confirm", "returns.manage", "purchases.view", "purchases.create", "purchases.approve", "purchases.receive", "suppliers.manage", "stock.transfers", "inventory.view", "inventory.count", "inventory.validate", "treasury.view", "treasury.transfer", "expenses.view", "expenses.create", "expenses.approve", "assets.view", "assets.manage", "stock.view", "stock.accept_counter", "team.view", "team.manage", "tables.view", "tables.manage", "finance.view", "reports.view", "reports.daily_close", "messages.view", "messages.send"],
  BARMAN: ["orders.view", "orders.create", "stock.view", "tables.view", "payments.create"],
  SECRETAIRE: ["orders.view", "team.view", "reports.view", "messages.view", "messages.send", "tables.view"],
  COMPTABLE: ["finance.view", "reports.view", "invoices.view", "quotes.view", "purchases.view", "inventory.view", "treasury.view", "treasury.transfer", "expenses.view", "expenses.create", "assets.view", "assets.manage"],
  APPROVISIONNEMENT: ["stock.view", "stock.receive", "stock.issue", "purchases.view", "purchases.create", "purchases.receive", "suppliers.manage", "stock.transfers", "reports.view"],
  CUISINIER: ["orders.view", "orders.prepare", "orders.handoff"],
  CHEF_CUISINE: ["orders.view", "orders.prepare", "stock.view", "stock.accept_kitchen", "products.manage", "messages.view", "messages.send"],
  GYM: ["services.view", "payments.create", "power.view"],
  AUBERGE: ["services.view", "payments.create", "power.view"],
  LAVAGE: ["services.view", "payments.create", "power.view"],
  WIFI: ["services.view", "payments.create", "power.view"],
  SECURITE: ["power.view"],
  INVENTAIRE: ["stock.view", "stock.audit", "inventory.view", "inventory.count", "reports.view"],
  GERANT_ADJOINT: ["orders.view", "orders.prepare", "orders.handoff", "quotes.view", "quotes.create", "quotes.convert", "invoices.view", "cash.view", "cash.manage", "cash.close", "stock.view", "stock.accept_counter", "team.view", "team.manage", "tables.view", "tables.manage", "finance.view", "reports.view", "reports.daily_close", "messages.view", "messages.send", "activities.view", "services.view", "power.view"],
  CAISSIER: ["finance.view", "payments.create", "cash.view", "cash.manage", "cash.close", "reports.view", "invoices.view", "power.view"],
  ADMINISTRATEUR: permissionCatalog.map((permission) => permission.key),
};

export const roleLabels: Record<string, string> = {
  SERVEUR: "Serveur", VENDEUR: "Vendeur / Commercial", SUPERVISEUR: "Superviseur", MAGASINIER: "Magasinier", GERANT: "Gérant", BARMAN: "Barman", SECRETAIRE: "Secrétaire", COMPTABLE: "Comptable", APPROVISIONNEMENT: "Approvisionnement", CUISINIER: "Cuisinier", CHEF_CUISINE: "Chef cuisine", SECURITE: "Sécurité", INVENTAIRE: "Chargé d’inventaire", GYM: "Équipe gym", AUBERGE: "Équipe auberge", LAVAGE: "Équipe lavage", WIFI: "Équipe Wi-Fi", GERANT_ADJOINT: "Gérant adjoint", CAISSIER: "Caissier", ADMINISTRATEUR: "Administrateur",
};
