"use client";
// DebitManager Power service support: activity-specific workspace shell, keeping clients, subscriptions, cash and occupancy discoverable.
import { useEffect, useState } from "react";
export function ServiceSupportClient({ tenantId, kind }: { tenantId: string; kind: "clients" | "subscriptions" | "cash" | "occupancy" }) {
  const labels = { clients: "Clients", subscriptions: "Abonnements", cash: "Caisse de l’activité", occupancy: "Occupation des chambres" } as const;
  const [name, setName] = useState(""); const [items, setItems] = useState<Array<{ id: string; label: string; detail?: string }>>([]); const [message, setMessage] = useState("");
  useEffect(() => { if (kind !== "cash" && kind !== "occupancy") fetch(`/api/power/service-sales?tenantId=${tenantId}&activityCode=${kind === "subscriptions" ? "GYM" : "GYM"}`, { cache: "no-store" }).then((r) => r.json()).then((data) => setItems((data.sales ?? []).map((sale: { id: string; customer_name: string; total_amount_xof: number; membership_expires_at?: string }) => ({ id: sale.id, label: sale.customer_name, detail: `${sale.total_amount_xof} XOF${sale.membership_expires_at ? ` · échéance ${new Date(sale.membership_expires_at).toLocaleDateString("fr-FR")}` : ""}` })))).catch(() => setMessage("Impossible de charger les données de cette section.")); }, [tenantId, kind]);
  return <section><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--secondary)]">Power · BAR SANTE PLUS</p><h1 className="mt-3 text-4xl font-black text-[var(--primary)]">{labels[kind]}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">Cet espace est séparé des stocks et suit les opérations de l’activité concernée.</p>{message && <p role="alert" className="mt-6 rounded-lg bg-[#ffdad6] px-4 py-3 text-sm font-bold text-[var(--danger)]">{message}</p>}<div className="mt-8 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--line)] pb-5"><div><p className="text-xs font-black uppercase tracking-[0.15em] text-[var(--muted)]">Registre</p><h2 className="mt-2 text-xl font-black text-[var(--primary)]">Suivi opérationnel</h2></div>{kind === "clients" && <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Rechercher un client" className="h-10 rounded-lg border border-[var(--line)] bg-[var(--background)] px-3 text-sm" />}</div>{kind === "cash" && <div className="py-12 text-sm text-[var(--muted)]">Les encaissements de cette activité apparaissent automatiquement dans le journal de caisse dès qu’une prestation est enregistrée.</div>}{kind === "occupancy" && <div className="py-12 text-sm text-[var(--muted)]">La vue d’occupation sera alimentée par les chambres et les séjours enregistrés dans l’activité Auberge.</div>}{kind !== "cash" && kind !== "occupancy" && (items.filter((i) => i.label.toLowerCase().includes(name.toLowerCase())).length ? <div className="divide-y divide-[var(--line)]">{items.filter((i) => i.label.toLowerCase().includes(name.toLowerCase())).map((item) => <div key={item.id} className="flex justify-between gap-4 py-4"><strong className="text-[var(--primary)]">{item.label}</strong><span className="text-sm text-[var(--muted)]">{item.detail}</span></div>)}</div> : <div className="py-12 text-sm text-[var(--muted)]">Aucune donnée enregistrée pour le moment.</div>)}</div></section>;
}
