/* Maquette choixprofil: deux parcours distincts, carte de création ou rattachement, palette DebitManager et interaction mobile-first. */
"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function ChooseProfilePage() {
  const router = useRouter();
  const [joining, setJoining] = useState(false);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");

  return <main className="min-h-screen bg-[var(--background)] px-5 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/" className="text-sm font-black text-[var(--primary)]">← DebitManager</Link><div className="mx-auto max-w-3xl py-14 text-center sm:py-20"><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--secondary)]">Étape suivante</p><h1 className="mt-4 text-4xl font-black tracking-[-0.04em] text-[var(--primary)] sm:text-5xl">Comment souhaitez-vous commencer ?</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-[var(--muted)]">Choisissez le parcours qui correspond à votre situation dans l’établissement.</p><div className="mt-12 grid gap-5 text-left md:grid-cols-2"><button type="button" onClick={() => router.push("/creationboutique")} className="group rounded-xl border-2 border-[var(--primary)] bg-[var(--surface)] p-7 text-left transition hover:-translate-y-1 hover:shadow-[0_18px_40px_-25px_var(--primary)]"><span className="flex h-12 w-12 items-center justify-center rounded-lg bg-[var(--accent-soft)] text-2xl text-[var(--primary)]">＋</span><h2 className="mt-7 text-2xl font-black text-[var(--primary)]">Créer ma boutique</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Je suis gérant ou propriétaire et je veux configurer mon propre établissement.</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-black text-[var(--primary)]">Commencer <span className="transition group-hover:translate-x-1">→</span></span></button><div className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-7"><button type="button" onClick={() => setJoining((value) => !value)} className="w-full text-left"><span className="flex h-12 w-12 items-center justify-center rounded-lg bg-[var(--surface-muted)] text-xl text-[var(--primary)]">↗</span><h2 className="mt-7 text-2xl font-black text-[var(--primary)]">Rejoindre une boutique</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">J’ai reçu un code d’invitation de la part d’un établissement existant.</p><span className="mt-8 inline-flex text-sm font-black text-[var(--primary)]">Saisir un code →</span></button>{joining && <form onSubmit={(event) => { event.preventDefault(); setError("Le rattachement par code sera activé avec l’invitation de votre établissement."); }} className="mt-7 border-t border-[var(--line)] pt-6"><label className="block text-sm font-bold text-[var(--ink)]">Code de la boutique<input value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="DMXXXXXXXX" className="mt-2 h-12 w-full rounded-lg border border-[var(--line)] bg-[var(--background)] px-4 uppercase outline-none focus:border-[var(--primary)]" /></label>{error && <p className="mt-3 text-xs font-bold text-[var(--danger)]">{error}</p>}<button className="mt-4 h-11 w-full rounded-lg bg-[var(--primary)] text-sm font-black text-white">Continuer avec ce code</button></form>}</div></div></div></div></main>;
}
