/* DebitManager Power owner sales: crafted reporting view with real paid revenue and responsive visual summaries. */
"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useLiveRefresh } from "@/hooks/useLiveRefresh";

type Activity = { name: string; amount: number; orderCount: number; units: number; note?: string };
type Person = { name: string; amount: number; orderCount: number };
type Data = { metrics: { totalRevenue: number; paidOrderCount: number; averageBasket: number }; activities: Activity[]; people: Person[]; daily: { date: string; amount: number }[] };
const money = (value: number) => `${new Intl.NumberFormat("fr-FR").format(value)} XOF`;
const activityColors: Record<string, string> = { Boissons: "#c8942f", Repas: "#17623c", Gym: "#2457a6", Auberge: "#8c5a3c", "Wi-Fi": "#5d3ea8", Lavage: "#176d64" };

export function SalesClient({ companyName }: { companyName: string }) {
  const [range, setRange] = useState("today"); const [person, setPerson] = useState(""); const [activity, setActivity] = useState(""); const [data, setData] = useState<Data | null>(null); const [peopleOptions, setPeopleOptions] = useState<{ id: string; name: string }[]>([]); const [error, setError] = useState("");
  const refresh = useCallback(async () => { const response = await fetch(`/api/dashboard/sales?range=${range}`, { cache: "no-store" }); if (!response.ok) { setError("Impossible de charger le chiffre d’affaires."); return; } const next = await response.json(); setData(next); setPeopleOptions(next.peopleOptions ?? []); setError(""); }, [range]);
  useEffect(() => { void refresh(); }, [refresh]); useLiveRefresh(refresh);
  const selectedActivity = useMemo(() => data?.activities.filter((item) => !activity || item.name === activity) ?? [], [data, activity]);
  const maxDaily = Math.max(...(data?.daily.map((item) => item.amount) ?? [1]), 1);
  const maxActivity = Math.max(...(selectedActivity.map((item) => item.amount) ?? [1]), 1);
  const filteredPeople = useMemo(() => data?.people.filter((item) => !person || item.name === peopleOptions.find((option) => option.id === person)?.name) ?? [], [data, person, peopleOptions]);
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--secondary)]">Propriétaire · {companyName}</p><h1 className="mt-3 text-4xl font-black tracking-[-0.05em] text-[var(--primary)]">Vente</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Le chiffre d’affaires homologué par paiement, analysé par activité et par personne.</p></div><span className="rounded-full bg-[var(--accent-soft)] px-3 py-2 text-xs font-black text-[var(--primary)]">Ventes payées uniquement</span></div>
    <div className="flex flex-wrap gap-2 rounded-2xl bg-[var(--surface)] p-4 shadow-[0_10px_35px_rgba(45,38,29,0.06)]"><select value={range} onChange={(event) => setRange(event.target.value)} className="rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3 py-2 text-sm font-bold text-[var(--primary)]"><option value="today">Aujourd’hui</option><option value="7d">7 derniers jours</option><option value="30d">30 derniers jours</option><option value="90d">90 derniers jours</option></select><select value={activity} onChange={(event) => setActivity(event.target.value)} className="rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3 py-2 text-sm font-bold text-[var(--primary)]"><option value="">Toutes les activités</option>{data?.activities.map((item) => <option key={item.name} value={item.name}>{item.name}</option>)}</select><select value={person} onChange={(event) => setPerson(event.target.value)} className="rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3 py-2 text-sm font-bold text-[var(--primary)]"><option value="">Toutes les personnes</option>{peopleOptions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    {error && <div role="alert" className="rounded-xl border border-[#f0c8c8] bg-[#fff2f2] px-4 py-3 text-sm font-bold text-[#8c2525]">{error}</div>}
    {!data ? <div className="rounded-2xl bg-[var(--surface)] p-8 text-sm text-[var(--muted)]">Chargement du chiffre d’affaires…</div> : <><div className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl bg-[var(--primary)] p-5 text-white shadow-[0_18px_40px_-24px_var(--primary)]"><p className="text-xs font-black uppercase tracking-[0.12em] text-white/60">Chiffre d’affaires</p><p className="mt-4 text-2xl font-black">{money(data.metrics.totalRevenue)}</p></article><article className="rounded-2xl bg-[var(--surface)] p-5 shadow-[0_10px_35px_rgba(45,38,29,0.06)]"><p className="text-xs font-black uppercase tracking-[0.12em] text-[var(--muted)]">Ventes homologuées</p><p className="mt-4 text-2xl font-black text-[var(--primary)]">{data.metrics.paidOrderCount}</p></article><article className="rounded-2xl bg-[var(--surface)] p-5 shadow-[0_10px_35px_rgba(45,38,29,0.06)]"><p className="text-xs font-black uppercase tracking-[0.12em] text-[var(--muted)]">Panier moyen</p><p className="mt-4 text-2xl font-black text-[var(--primary)]">{money(data.metrics.averageBasket)}</p></article></div>
    <section className="rounded-2xl bg-[var(--surface)] p-6 shadow-[0_10px_35px_rgba(45,38,29,0.06)]"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-[var(--secondary)]">Tendance</p><h2 className="mt-2 text-xl font-black text-[var(--primary)]">Évolution du chiffre d’affaires</h2></div><span className="text-xs font-bold text-[var(--muted)]">{data.daily.length} jour{data.daily.length > 1 ? "s" : ""}</span></div><div className="mt-7 flex h-44 items-end gap-1 overflow-hidden sm:gap-2">{data.daily.map((item) => <div key={item.date} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div title={`${item.date} · ${money(item.amount)}`} className="w-full max-w-8 rounded-t-md bg-[var(--secondary)] transition-opacity group-hover:opacity-70" style={{ height: `${Math.max((item.amount / maxDaily) * 100, item.amount ? 7 : 2)}%` }} /><span className="hidden -rotate-45 text-[9px] font-bold text-[var(--muted)] sm:block">{item.date.slice(5)}</span></div>)}</div></section>
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl bg-[var(--surface)] p-6 shadow-[0_10px_35px_rgba(45,38,29,0.06)]"><p className="text-xs font-black uppercase tracking-[0.14em] text-[var(--secondary)]">Répartition</p><h2 className="mt-2 text-xl font-black text-[var(--primary)]">Chiffre d’affaires par activité</h2><div className="mt-6 space-y-4">{selectedActivity.map((item) => <div key={item.name}><div className="flex justify-between gap-3 text-sm"><span className="font-black text-[var(--primary)]">{item.name}</span><span className="font-black text-[var(--primary)]">{money(item.amount)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--surface-muted)]"><div className="h-full rounded-full" style={{ width: `${item.amount ? Math.max((item.amount / maxActivity) * 100, 4) : 2}%`, backgroundColor: activityColors[item.name] ?? "var(--secondary)" }} /></div><p className="mt-1 text-xs text-[var(--muted)]">{item.orderCount} ligne{item.orderCount > 1 ? "s" : ""} · {item.units} unité{item.units > 1 ? "s" : ""}{item.note ? ` · ${item.note}` : ""}</p></div>)}</div></section><section className="rounded-2xl bg-[var(--surface)] p-6 shadow-[0_10px_35px_rgba(45,38,29,0.06)]"><p className="text-xs font-black uppercase tracking-[0.14em] text-[var(--secondary)]">Performance</p><h2 className="mt-2 text-xl font-black text-[var(--primary)]">Chiffre d’affaires par personne</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[430px] text-left text-sm"><thead className="border-b border-[var(--line)] text-xs uppercase tracking-[0.1em] text-[var(--muted)]"><tr><th className="pb-3">Personne</th><th className="pb-3">Commandes</th><th className="pb-3 text-right">CA</th></tr></thead><tbody>{filteredPeople.map((item) => <tr key={item.name} className="border-b border-[var(--line)] last:border-0"><td className="py-4 font-black text-[var(--primary)]">{item.name}</td><td className="py-4 text-[var(--muted)]">{item.orderCount}</td><td className="py-4 text-right font-black text-[var(--primary)]">{money(item.amount)}</td></tr>)}</tbody></table>{!filteredPeople.length && <p className="py-8 text-sm text-[var(--muted)]">Aucune vente payée pour ces filtres.</p>}</div></section></div></>}
  </div>;
}
